exclude:
  - '**/vendor/**/*'
  - '**/node_modules/**/*'

  - 'app/views/users/registrations/new.html.erb' # todo: Line is too long at line 56.
  - 'app/views/users/sessions/new.html.erb' # todo:  Line is too long at line 38.
  - 'app/views/to_let_go_items/_form.html.erb' # todo:  Line is too long at line 37.
  - 'app/views/quotes/index.html.erb' # todo:  Line is too long at line 7.

EnableDefaultLinters: true
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Style/FrozenStringLiteralComment:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Style/RedundantEach:
        Enabled: false # viewでeachがあると全てエラーになってしまう "An error occurred while SR cop was inspecting *.html.erb"