exclude:
  - '**/vendor/**/*'
  - '**/node_modules/**/*'
  - 'app/views/users/shared/**' # todo: Style/RedundantEach cop was inspecting ?
  - 'app/views/shared/_flash_messages.html.erb' # todo: Style/RedundantEach cop was inspecting ?
  - 'app/views/users/registrations/new.html.erb' # todo: Line is too long at line 56. スタイルを減らす？
  - 'app/views/users/sessions/new.html.erb' # todo:  Line is too long at line 38. スタイルを減らす？

EnableDefaultLinters: true
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Style/FrozenStringLiteralComment:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false