inherit_from: .rubocop_todo.yml
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  # RuboCopのバージョンがあがった際に追加されたCopを自動で有効に
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  StyleGuideBaseURL: https://github.com/fortissimo1997/ruby-style-guide/blob/japanese/README.ja.md
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'app/controllers/users/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false