version: "3.9"
services:
  web:
    build: .
    command: bash -c "rm -f karoyaka/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/karoyaka:cached
      - bundle:/usr/local/bundle
    ports:
      - '3001:3000'
    depends_on:
      - db
      - chrome
      - redis
      - sidekiq
    stdin_open: true
    tty: true
    environment:
      MYSQL_PASSWORD: password
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
      REDIS_URL: redis://redis:6379

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  chrome:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - '4444:4444'

  sidekiq:
    build: .
    environment:
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/karoyaka:cached
      - bundle:/usr/local/bundle
    depends_on:
      - db
      - redis
    command: bundle exec sidekiq

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  bundle:
  mysql_data:
  redis: